[{"TimeUTC":"2024-12-19 05:03:46","timestampInMs":1734584626092,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-1,"requestId":"v4t4f-1734584625804-69cb133f967d","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:45","timestampInMs":1734584625847,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"v4t4f-1734584625804-69cb133f967d","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":231,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:43","timestampInMs":1734584623691,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-1,"requestId":"nqztt-1734584623399-bc538133eba3","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:43","timestampInMs":1734584623436,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"nqztt-1734584623399-bc538133eba3","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":241,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:42","timestampInMs":1734584622290,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-1,"requestId":"n5m52-1734584622008-93a443110776","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:42","timestampInMs":1734584622046,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"n5m52-1734584622008-93a443110776","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":229,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:41","timestampInMs":1734584621969,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"zq7bt-1734584621682-212313d81c0e","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:41","timestampInMs":1734584621717,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"zq7bt-1734584621682-212313d81c0e","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":237,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620851,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"n5xl7-1734584620557-e8f8054cd342","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620797,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"kpngl-1734584620515-eff98f07da77","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620597,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"n5xl7-1734584620557-e8f8054cd342","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":239,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620586,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"nttbt-1734584620298-362145eb3c35","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620551,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"kpngl-1734584620515-eff98f07da77","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":231,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620335,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"nttbt-1734584620298-362145eb3c35","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":237,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620309,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"wjmzg-1734584619996-a9d50c52ad3b","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620153,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"c8qlp-1734584619608-b6ec18956055","requestUserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:40","timestampInMs":1734584620032,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"wjmzg-1734584619996-a9d50c52ad3b","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":259,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:39","timestampInMs":1734584619904,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"c8qlp-1734584619608-b6ec18956055","requestUserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":236,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:39","timestampInMs":1734584619790,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"b9jxd-1734584619511-60a2c97006cd","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:39","timestampInMs":1734584619599,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"cnsww-1734584619293-ba762adaeb36","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:39","timestampInMs":1734584619548,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"b9jxd-1734584619511-60a2c97006cd","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":230,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:39","timestampInMs":1734584619329,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"cnsww-1734584619293-ba762adaeb36","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":254,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:38","timestampInMs":1734584618432,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"mm799-1734584618137-b233ed3fb7a3","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:38","timestampInMs":1734584618419,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"tbftm-1734584618128-4987d180da49","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:38","timestampInMs":1734584618231,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"5fsdm-1734584617938-f2937136a805","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:38","timestampInMs":1734584618198,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"bfckk-1734584617918-6450906176ed","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:38","timestampInMs":1734584618177,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"mm799-1734584618137-b233ed3fb7a3","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":240,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:38","timestampInMs":1734584618171,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"tbftm-1734584618128-4987d180da49","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":230,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617973,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"5fsdm-1734584617938-f2937136a805","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":242,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617955,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"bfckk-1734584617918-6450906176ed","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":229,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617893,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"pl57m-1734584617335-34057dc1726a","requestUserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617811,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"lln2b-1734584617500-5d9a0b302b18","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617770,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"pk7tv-1734584617465-cd458e03298d","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617709,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"clc5c-1734584617375-e8e4563a22f6","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617634,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"pl57m-1734584617335-34057dc1726a","requestUserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":242,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617555,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"5c8l5-1734584617268-92e260bbd08e","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617542,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"lln2b-1734584617500-5d9a0b302b18","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":254,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617514,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"pk7tv-1734584617465-cd458e03298d","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":240,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617435,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"lln2b-1734584617152-fb6ce94ae20e","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617433,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"clc5c-1734584617375-e8e4563a22f6","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":238,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617305,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"5c8l5-1734584617268-92e260bbd08e","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":235,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617190,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"lln2b-1734584617152-fb6ce94ae20e","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":231,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617129,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"9jgff-1734584616771-19c61ef4b93e","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617035,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"bdbfj-1734584616684-d673cd7dc353","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617030,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"lg6ps-1734584616641-81b3ddbe2d15","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617027,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"2gxsc-1734584616681-5fc1d97d9ce8","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:37","timestampInMs":1734584617021,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"9jgff-1734584616707-4752651f2cfb","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616885,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"7wl8h-1734584616596-ce13f7e8d857","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616806,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"9jgff-1734584616771-19c61ef4b93e","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":236,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616782,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"bdbfj-1734584616684-d673cd7dc353","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":235,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616776,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"254qf-1734584616034-a9418a0a6c4d","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616772,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"9jgff-1734584616707-4752651f2cfb","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":234,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616766,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"lg6ps-1734584616641-81b3ddbe2d15","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":245,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616764,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"2gxsc-1734584616681-5fc1d97d9ce8","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":249,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616633,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"7wl8h-1734584616596-ce13f7e8d857","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":236,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616454,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"hlxxl-1734584615665-e954a633f038","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616431,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"vfgkn-1734584615607-4da2ba00c649","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616400,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"lg6ps-1734584615529-fef0848954ee","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616357,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"rxhzr-1734584615956-2cec9c2756fc","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616106,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"254qf-1734584616034-a9418a0a6c4d","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":229,"region":"iad1","maxMemoryUsed":46,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616097,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"rxhzr-1734584615956-2cec9c2756fc","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":239,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:36","timestampInMs":1734584616017,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"wfzw8-1734584615556-90f9636e3af2","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/api/index.py\", line 19, in <module>\nif root_dir not in sys.path:\n^^^\nNameError: name 'sys' is not defined. Did you forget to import 'sys'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:35","timestampInMs":1734584615784,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"hlxxl-1734584615665-e954a633f038","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":239,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:35","timestampInMs":1734584615753,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"lg6ps-1734584615529-fef0848954ee","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":237,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:35","timestampInMs":1734584615751,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"vfgkn-1734584615607-4da2ba00c649","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":243,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"},{"TimeUTC":"2024-12-19 05:03:35","timestampInMs":1734584615750,"requestPath":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"wfzw8-1734584615556-90f9636e3af2","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/api/index.py","host":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentDomain":"insta-analysis-3c3k4pkwl-hyunils-projects.vercel.app","deploymentId":"dpl_6DjSQDhEKbmt46bHXLCip8QcNmYq","durationMs":244,"region":"iad1","maxMemoryUsed":45,"memorySize":1024,"message":"","projectId":"prj_pdXNpNzcyIALXwyQJfTG9C9mLb6c"}]